'use client';

import { createContext, useContext, useEffect, useMemo, useSyncExternalStore } from 'react';

export type Locale = 'en' | 'rw';
type Dictionary = Record<string, string>;

const dictionaries: Record<Locale, Dictionary> = {
  en: {
    home: 'Home', documentaries: 'Documentaries', about: 'About', pricing: 'Pricing', login: 'Login', register: 'Register', account: 'My account', logout: 'Log out',
    subscribe: 'Subscribe', exploreLibrary: 'Explore the library', heroTitle: 'Watch Aime Christian Documentaries Ad-Free',
    heroEyebrow: 'Independent documentaries', heroTitleLead: 'Watch Aime Christian Documentaries', heroTitleAccent: 'Ad-Free', heroDescription: 'Premium access to advertisement-free Rwandan stories and investigations.',
    language: 'Language', english: 'English', kinyarwanda: 'Kinyarwanda', active: 'Active', pending: 'Being confirmed', free: 'Free',
    explore: 'Explore', legal: 'Legal', paymentInfo: 'Pay instantly with MTN MoMo, Airtel Money or card.', footerDescription: 'The home for independent documentaries and current stories from Rwanda and beyond.',
    privacy: 'Privacy Policy', terms: 'Terms of Service', chooseAccess: 'Choose your access', payMomo: 'Pay with mobile money or card', uploadProof: 'Approve and start watching', payNow: 'Pay with MTN MoMo',
    waiting: 'Payment submitted successfully. Your payment is waiting for verification. Access is activated only after an administrator confirms it.',
    premium: 'Premium content', youHaveAccess: 'You have access', watchDocumentary: 'Watch Documentary', backToDocumentaries: 'Back to documentaries', watchTrailer: 'Watch trailer', noTrailer: 'No trailer available.',
    daysLeft: '{n} days left',
  },
  rw: {
    home: 'Ahabanza', documentaries: 'Ibyegeranyo', about: 'Ibitwerekeye', pricing: 'Ibiciro', login: 'Injira', register: 'Iyandikishe', account: 'Konti yanjye', logout: 'Sohoka',
    subscribe: 'Iyandikishe', exploreLibrary: 'Reba ibiri muri porogaramu', heroTitle: 'Reba filimi mbarankuru za Aime Christian nta matangazo',
    heroEyebrow: 'Filimi mbarankuru zigenga', heroTitleLead: 'Reba filimi mbarankuru za Aime Christian', heroTitleAccent: 'nta matangazo', heroDescription: 'Kwamamaza inkuru n’iperereza by’u Rwanda nta matangazo.',
    language: 'Ururimi', english: 'Icyongereza', kinyarwanda: 'Ikinyarwanda', active: 'Birakora', pending: 'Biri kwemezwa', free: 'Ubuntu',
    explore: 'Reba', legal: 'Amategeko', paymentInfo: 'Ishyura ako kanya ukoresheje MTN MoMo, Airtel Money cyangwa ikarita.', footerDescription: 'Aho warebera filimi mbarankuru n’inkuru z’u Rwanda n’ahandi.',
    privacy: 'Amabwiriza y’ibanga', terms: 'Amabwiriza yo gukoresha', chooseAccess: 'Hitamo uburyo bwo kureba', payMomo: 'Ishyura ukoresheje Mobile Money cyangwa ikarita', uploadProof: 'Emeza utangire kureba', payNow: 'Ishyura ukoresheje MTN MoMo',
    waiting: 'Icyemezo cy’ishyuwa cyoherejwe neza. Icyishyurwa cyawe kirategereje kwemezwa. Uburenganzira buzatangwa ari uko umuyobozi abyemeje.',
    premium: 'Ibikubiyemo byishyurwa', youHaveAccess: 'Ufite uburenganzira', watchDocumentary: 'Reba filimi mbarankuru', backToDocumentaries: 'Subira ku zindi filimi', watchTrailer: 'Reba agace gato', noTrailer: 'Nta gace gato kaboneka.',
    'About Aime Christian': 'Kwamamaza kuri Aime Christian', 'Featured Documentaries': 'Filimi mbarankuru zatoranyijwe', 'Recently Added': 'Izongewe vuba', 'Choose Your Plan': 'Hitamo gahunda yawe', 'Most Popular': 'Ikunzwe cyane', 'Get Started': 'Tangira',
    'No documentaries available yet.': 'Nta filimi mbarankuru ziraboneka.', 'No featured documentaries available yet.': 'Nta filimi mbarankuru zatoranyijwe ziraboneka.', 'The latest documentaries added to our collection.': 'Filimi mbarankuru ziheruka kongerwa mu ikusanyirizo ryacu.',
    'Discover our most compelling stories and investigations from Rwanda and beyond.': 'Menya inkuru n’iperereza byacu by’ingenzi byo mu Rwanda n’ahandi.', 'Get unlimited access to all documentaries with our flexible subscription plans.': 'Reba filimi mbarankuru zose ukoresheje gahunda zacu zoroshye.',
    'Back': 'Subira inyuma', 'Open player': 'Fungura ahareberwa', 'Subscribe now': 'Iyandikishe ubu', 'Ready to watch': 'Witeguye kureba', 'Subscribe to watch this documentary': 'Iyandikishe urebe iyi filimi mbarankuru', 'About this documentary': 'Ibyerekeye iyi filimi mbarankuru', 'Access Status': 'Uko uburenganzira buhagaze', 'Watch this documentary ad-free': 'Reba iyi filimi mbarankuru nta matangazo', 'Buy only this documentary · 200 RWF': 'Gura iyi filimi mbarankuru gusa · 200 RWF',
    'Create your account': 'Fungura konti yawe', 'Full name': 'Amazina yose', 'Rwanda phone number': 'Nimero ya telefoni y’u Rwanda', 'Phone number': 'Nimero ya telefoni', 'Password': 'Ijambo banga', 'Continue to payment': 'Komeza ujye kwishyura', 'Welcome back': 'Murakaza neza', 'Signing in…': 'Kwamamaza…', 'New here?': 'Uri mushya?', 'Create an account': 'Fungura konti', 'Already a member?': 'Usanzwe uri umunyamuryango?', 'At least 6 characters.': 'Nibura inyuguti 6.',
    'YOUR ACCOUNT': 'KONTI YANJYE', 'Access status': 'Uko uburenganzira buhagaze', 'Account details': 'Amakuru ya konti', 'Payment waiting for verification': 'Ishyurwa ritegereje kwemezwa', 'Access has ended': 'Uburenganzira bwarangiye', 'Full access': 'Uburenganzira bwose', 'No active subscription': 'Nta kwiyandikisha gukora', 'Choose a plan': 'Hitamo gahunda', 'Renew subscription': 'Ongera kwiyandikisha', 'Individual documentary access:': 'Uburenganzira bwa filimi imwe:',
    'MEMBERSHIP': 'UBUNYAMURYANGO', 'Stories worth staying for.': 'Inkuru zikwiye umwanya wawe.', 'Pay with MTN MoMo, upload your proof, and receive access once an administrator verifies the payment.': 'Ishyura ukoresheje MTN MoMo, ohereza icyemezo, ubone uburenganzira umuyobozi amaze kwemeza ishyurwa.',
    'Privacy Policy': 'Amabwiriza y’ibanga', 'Terms of Service': 'Amabwiriza yo gukoresha', 'LEGAL': 'AMATEGEKO', 'Last updated: September 2, 2026': 'Bivuguruye: 2 Nzeri 2026', 'Unable to load this page': 'Ntibyashobotse gufungura uru rupapuro', 'Please check your connection and try again.': 'Reba interineti yawe hanyuma wongere ugerageze.', 'Try again': 'Ongera ugerageze',
    'Choose or drop a payment screenshot': 'Hitamo cyangwa ukurure ifoto y’ishyuwa', 'Remove payment proof': 'Kuraho icyemezo cy’ishyuwa', 'Payment proof preview': 'Igaragazambere ry’icyemezo cy’ishyuwa', 'Use the code on your MTN phone, then upload a clear screenshot. Payment is not automatic; access begins only after administrator verification.': 'Koresha kode kuri telefoni ya MTN, hanyuma wohereze ifoto isobanutse. Ishyurwa ntiryemezwa ako kanya; uburenganzira butangira umuyobozi abyemeje.',
    'ABOUT AIME CHRISTIAN': 'IBYEREKEYE AIME CHRISTIAN', 'Stories with the patience to look closer.': 'Inkuru zirebwa mu bwitonzi bwimbitse.', 'Ibyegeranyo is Aime Christian’s home for independent documentary work: a place to follow the people, systems and choices that shape Rwanda and its place in the world.': 'Ibyegeranyo ni urubuga rwa Aime Christian rwa filimi mbarankuru zigenga, rwerekana abantu, imikorere n’amahitamo bihindura u Rwanda n’umwanya warwo ku isi.', 'WHAT WE COVER': 'IBYO TWIBANDAHO', 'History': 'Amateka', 'Economics': 'Ubukungu', 'Politics': 'Politiki', 'Social welfare': 'Imibereho myiza', 'Lifestyle': 'Imibereho', 'Diplomacy': 'Diplomasi', 'Investigations': 'Iperereza', 'Current affairs': 'Amakuru agezweho', 'Support independent viewing.': 'Shyigikira kureba kwigenga.', 'Membership helps sustain thoughtful reporting while giving you an ad-free, focused place to watch.': 'Kwamamaza bifasha gukomeza itangazamakuru ryimbitse kandi biguha aho urebera nta matangazo.', 'Explore documentaries': 'Reba filimi mbarankuru', 'View pricing': 'Reba ibiciro',
    'Explore our complete collection of premium documentaries. Watch compelling stories and investigations from Rwanda and beyond.': 'Reba ikusanyirizo ryuzuye rya filimi mbarankuru zacu. Reba inkuru n’iperereza bivuye mu Rwanda n’ahandi.', 'CURATED STORIES': 'INKURU ZATORANYIJWE', 'NEW RELEASES': 'IZONGEWE VUBA',
    'Documentaries': 'Ibyegeranyo', 'About': 'Ibitwerekeye', 'Weekly': 'Icyumweru', 'Monthly': 'Ukwezi', 'Yearly': 'Umwaka', 'Single Documentary': 'Ikiganiro kimwe', '7 days access to all documentaries': 'Iminsi 7 yo kureba ibyegeranyo byose', '30 days access to all documentaries': 'Iminsi 30 yo kureba ibyegeranyo byose', '1 year access to all documentaries': 'Umwaka wose wo kureba ibyegeranyo byose', 'Access to one documentary for 30 days': 'Kureba ikiganiro kimwe iminsi 30', 'Full documentary access': 'Uburenganzira bwo kureba ibyegeranyo byose', 'Ad-free viewing': 'Kureba nta matangazo', 'Watch on any device': 'Rebera ku gikoresho icyo ari cyo cyose', 'Best value': 'Agaciro keza', 'Best savings': 'Kuzigama cyane', 'One documentary access': 'Uburenganzira bw’ikiganiro kimwe', '30 days access': 'Uburenganzira bw’iminsi 30', 'days': 'iminsi', 'All payments are processed manually via MTN MoMo. Access is granted after verification.': 'Kwishyura byose bigenzurwa n’umuyobozi binyuze muri MTN MoMo. Uburenganzira butangwa nyuma yo kwemezwa.',
    'Ready to Start Watching?': 'Witeguye gutangira kureba?', 'Join now and get unlimited access to premium documentaries from Rwanda and around the world. Ad-free, high-quality content.': 'Iyandikishe ubu urebe ibyegeranyo byiza byo mu Rwanda n’ahandi nta mupaka. Nta matangazo, bifite ireme.', 'Subscribe Now': 'Iyandikishe ubu', 'Browse Documentaries': 'Reba ibyegeranyo', 'ABOUT IBYEGERANYO': 'IBYEREKEYE IBYEGERANYO', 'Ibyegeranyo is a home for documentaries people can watch without advertising: a focused, uninterrupted place for stories that deserve your full attention.': 'Ibyegeranyo ni urubuga rw’ibyegeranyo wareba nta matangazo: ahantu hatuje hagenewe inkuru zikwiye kwitabwaho kwawe kose.', 'Our collection follows the people, systems and choices shaping Rwanda and its place in the world. Expect thoughtful documentaries on history, economics, politics, social welfare, lifestyle, diplomacy, investigations and current affairs.': 'Ikusanyirizo ryacu rikurikirana abantu, imikorere n’amahitamo bihindura u Rwanda n’umwanya warwo ku isi. Uzabonamo ibyegeranyo byimbitse ku mateka, ubukungu, politiki, imibereho myiza, ubuzima, diplomasi, iperereza n’amakuru agezweho.', 'Every subscription supports an ad-free viewing experience, so you can spend time with each film without distractions.': 'Kwamamaza kwawe gushyigikira kureba nta matangazo, bityo ugahabwa umwanya wo kwishimira buri kiganiro nta kukurangaza.',
    'Information we collect': 'Amakuru dukusanya', 'How we use information': 'Uko dukoresha amakuru', 'Cookies and storage': 'Cookies n’ububiko', 'Security and retention': 'Umutekano n’igihe tubika amakuru', 'Your rights and contact': 'Uburenganzira bwawe n’itumanaho', 'Accounts and responsibilities': 'Konti n’inshingano', 'Payments and verification': 'Kwishyura no kwemezwa', 'Subscription duration': 'Igihe cyo kwiyandikisha', 'Content ownership and access': 'Nyir’ibikubiyemo n’uburenganzira', 'Availability and termination': 'Kuboneka no guhagarika serivisi', 'Changes and contact': 'Impinduka n’itumanaho',
    'We collect your name, Rwanda phone number, password hash, selected plan, subscription dates and payment status to provide your account. When you submit payment proof, we store the image and the information needed to manually verify it.': 'Dukusanya amazina yawe, nimero ya telefoni y’u Rwanda, ijambo banga ribitswe mu buryo bwizewe, gahunda wahisemo, amatariki yo kwiyandikisha n’imiterere y’ishyuwa kugira ngo konti yawe ikore. Iyo wohereje icyemezo cy’ishyuwa, tubika ifoto n’amakuru akenewe kugira ngo byemezwe n’umuyobozi.', 'We use this information to authenticate you, verify payments, grant access, prevent misuse, respond to support requests and improve the service. We do not sell personal information.': 'Dukoresha aya makuru kukumenya, kwemeza ubwishyu, gutanga uburenganzira, gukumira imikoreshereze mibi, gusubiza ubusabe bw’ubufasha no kunoza serivisi. Ntiducuruza amakuru yihariye.', 'Secure HTTP-only session cookies keep you signed in. We use hosting, database, video and storage providers to operate Ibyegeranyo. Their processing is limited to delivering the service.': 'Cookies z’umutekano zibika uko winjiye muri konti. Dukoresha abatanga serivisi zo kwakira urubuga, ububiko bw’amakuru, videwo n’amafayili kugira ngo Ibyegeranyo ikore. Amakuru yabo akoreshwa gusa mu gutanga serivisi.', 'Passwords are hashed; payment proofs and account records are restricted to authorised administrators. No system is perfectly secure, but we use reasonable safeguards and retain information only as long as needed for operations, legal obligations or dispute resolution.': 'Amagambo banga abikwa mu buryo bwizewe; ibyemezo by’ishyuwa n’amakuru ya konti bibonwa gusa n’abayobozi babyemerewe. Nta sisitemu itagira intege nke burundu, ariko dukoresha ingamba zikwiriye kandi tubika amakuru igihe akenewe gusa.', 'You may request access, correction or deletion of account information, subject to legal and operational requirements. Contact Ibyegeranyo through the platform’s official social channels for privacy questions. This policy may be updated; the current version on this page applies.': 'Ushobora gusaba kubona, gukosora cyangwa gusiba amakuru ya konti yawe, hubahirijwe amategeko n’imikorere ya serivisi. Twandikire Ibyegeranyo ukoresheje imbuga zayo zemewe ku bibazo by’ibanga. Aya mabwiriza ashobora kuvugururwa; akari kuri uru rupapuro ni yo akurikizwa.',
    'Provide accurate account information, keep your password private, and use your own account. You are responsible for activity under your account.': 'Tanga amakuru ya konti nyayo, bika ijambo banga ryawe mu ibanga kandi ukoreshe konti yawe bwite. Ufite inshingano ku bikorwa biba kuri konti yawe.', 'Payments are made through MTN MoMo and are not activated automatically. Uploading a payment proof creates a pending request; access begins only after an administrator confirms it. Rejected or unclear proofs may require resubmission.': 'Kwishyura bikorwa binyuze muri MTN MoMo kandi ntibihita byemezwa. Kohereza icyemezo cy’ishyuwa bituma ubusabe butegereza; uburenganzira butangira umuyobozi abyemeje. Ibyemezo byanze cyangwa bidasobanutse bishobora gusaba kongera koherezwa.', 'Weekly, monthly and yearly access lasts for the published number of days from confirmation. A 200 RWF single-documentary purchase grants access only to the selected documentary for 30 days; it does not provide a library subscription.': 'Uburenganzira bw’icyumweru, ukwezi n’umwaka bumara iminsi yatangajwe uhereye ku kwemezwa. Kugura ikiganiro kimwe kuri 200 RWF biguha uburenganzira bwo kukireba iminsi 30 gusa; ntibiguha uburenganzira ku ikusanyirizo ryose.', 'All documentaries, artwork and platform materials are owned by or licensed to Aime Christian Documentaries. You may view content for personal use only. Copying, recording, redistributing, sharing credentials, public screening or circumventing access controls is prohibited.': 'Ibyegeranyo byose, amashusho n’ibikoresho by’urubuga ni iby’Aime Christian Documentaries cyangwa byahawe uruhushya. Ushobora kubireba ku giti cyawe gusa. Gukoporora, gufata amajwi cyangwa amashusho, kubisakaza, gusangira konti, kubyereka benshi cyangwa kurenga ku igenzura ry’uburenganzira birabujijwe.', 'We aim to keep the service available, but availability can be affected by maintenance, networks or third-party services. We may suspend or terminate accounts that violate these terms or threaten the service.': 'Duharanira ko serivisi iboneka, ariko ishobora kubangamirwa n’ikorwa ry’isanwa, imiyoboro cyangwa serivisi z’abandi. Dushobora guhagarika konti zica aya mabwiriza cyangwa zibangamira serivisi.', 'We may change these terms as the service evolves. Continued use after an update means you accept the revised terms. Contact Ibyegeranyo through its official channels with questions.': 'Dushobora guhindura aya mabwiriza uko serivisi ikura. Gukomeza gukoresha urubuga nyuma y’ivugurura bivuze ko wemeye amabwiriza mashya. Twandikire Ibyegeranyo ku nzira zayo zemewe niba ufite ikibazo.',
    daysLeft: 'Hasigaye iminsi {n}',
    'Payment method': 'Uburyo bwo kwishyura', 'Approve payment': 'Emeza ishyurwa', 'Approve with your MoMo PIN': 'Emeza ukoresheje PIN ya MoMo', 'Approve with your Airtel PIN': 'Emeza ukoresheje PIN ya Airtel', 'Visa or Mastercard': 'Visa cyangwa Mastercard',
    'Email for your receipt': 'Imeli yo kwakiriraho inyemezabwishyu', 'MTN MoMo number': 'Nimero ya MTN MoMo', 'Airtel Money number': 'Nimero ya Airtel Money', 'Starting payment…': 'Gutangiza ishyurwa…', 'Pay': 'Ishyura',
    'Payment confirmed. Your access is active.': 'Ishyurwa ryemejwe. Uburenganzira bwawe burakora.', 'The payment was not completed.': 'Ishyurwa ntiryarangiye.', 'No access was granted. If money left your account, it will be matched automatically; contact us if access does not appear within a day.': 'Nta burenganzira bwatanzwe. Niba amafaranga yavuye kuri konti yawe, azahuzwa ubwayo; tuvugishe niba uburenganzira butagaragaye mu munsi umwe.',
    'Waiting for your payment': 'Dutegereje ishyurwa ryawe', 'Approve the payment on your phone or in the payment window. This page updates by itself.': 'Emeza ishyurwa kuri telefoni yawe cyangwa mu idirishya ryo kwishyura. Uru rupapuro rwihindura ubwarwo.', 'Checking payment status': 'Kugenzura uko ishyurwa rihagaze',
    'Payment being confirmed': 'Ishyurwa riri kwemezwa', 'Not completed': 'Ntiryarangiye', 'Pay with MTN MoMo, Airtel Money or card. Your access starts as soon as the payment is confirmed.': 'Ishyura ukoresheje MTN MoMo, Airtel Money cyangwa ikarita. Uburenganzira butangira ishyurwa rikimara kwemezwa.',
    'Use MTN MoMo, Airtel Money or a card. Mobile money sends a prompt to your phone.': 'Koresha MTN MoMo, Airtel Money cyangwa ikarita. Mobile Money yohereza ubutumwa kuri telefoni yawe.', 'Approve the payment and your access unlocks automatically.': 'Emeza ishyurwa maze uburenganzira bwawe bufunguke ubwabwo.',
    'Secure payments with MTN MoMo, Airtel Money or card. Access is granted automatically once paid.': 'Kwishyura kwizewe ukoresheje MTN MoMo, Airtel Money cyangwa ikarita. Uburenganzira butangwa ako kanya umaze kwishyura.',
    'View all': 'Reba byose', 'Watch now': 'Reba nonaha', 'Home': 'Ahabanza', 'Back to top': 'Subira hejuru', 'OUR COLLECTION': 'IKUSANYIRIZO RYACU', 'Search documentaries': 'Shakisha filimi mbarankuru', 'All': 'Byose', 'No documentaries match your search.': 'Nta filimi mbarankuru ihuye n’ibyo washakishije.', 'Clear search': 'Siba ibyo washakishije', 'JUST ADDED': 'BYONGEWEMO VUBA', 'Latest Documentary': 'Filimi mbarankuru iheruka', 'The newest release on Ibyegeranyo — available with your subscription.': 'Iheruka gushyirwa kuri Ibyegeranyo — iboneka mu kwiyandikisha kwawe.', 'HOW IT WORKS': 'UKO BIKORA', 'Start watching in three steps': 'Tangira kureba mu ntambwe eshatu', 'Pick weekly, monthly, yearly or a single documentary.': 'Hitamo icyumweru, ukwezi, umwaka cyangwa filimi mbarankuru imwe.', 'Dial the USSD code shown after you create your account.': 'Kanda kode ya USSD uzahabwa nyuma yo gufungura konti yawe.', 'An administrator verifies it and unlocks your access.': 'Umuyobozi arabyemeza maze agufungurira uburenganzira.', 'Single documentary': 'Filimi mbarankuru imwe', 'Access to one documentary for 7 days': 'Kureba filimi mbarankuru imwe mu minsi 7', 'One documentary': 'Filimi mbarankuru imwe', 'Best annual value': 'Agaciro keza ku mwaka', 'Back to documentaries': 'Subira ku zindi filimi', 'You have access': 'Ufite uburenganzira', 'Premium content': 'Ibikubiyemo byishyurwa', 'Watch trailer': 'Reba agace gato', 'No trailer available.': 'Nta gace gato kaboneka.', 'Buy only this documentary': 'Gura iyi filimi mbarankuru gusa', 'Sign in or subscribe to watch the full documentary. Until then, you can watch the trailer.': 'Injira cyangwa wiyandikishe kugira ngo urebe filimi mbarankuru yose. Hagati aho, ushobora kureba agace gato.', 'Your payment has not been confirmed or your access has ended. You can watch the trailer until access is active.': 'Ubwishyu bwawe ntiburemezwa cyangwa uburenganzira bwawe bwararangiye. Ushobora kureba agace gato kugeza igihe uburenganzira bukora.', 'Documentary not found': 'Filimi mbarankuru ntiyabonetse', 'Subscribe to Watch': 'Iyandikishe urebe', 'This full documentary is available after your subscription or single-documentary payment is verified.': 'Iyi filimi mbarankuru yose iboneka nyuma y’uko ubwishyu bwawe bwemejwe.', 'Log in': 'Injira', 'Show password': 'Erekana ijambo banga', 'Hide password': 'Hisha ijambo banga', 'Selected plan': 'Gahunda wahisemo', 'Change': 'Hindura', 'Creating account…': 'Gufungura konti…', 'Plan': 'Gahunda', 'Payment': 'Ubwishyu', 'Start': 'Itangiriro', 'Expires': 'Irangira', 'Confirmed': 'Byemejwe', 'Rejected': 'Byanzwe', 'Amount': 'Amafaranga', 'Copy': 'Koporora', 'Copied': 'Byakoporowe', 'Registered to Aime Christian': 'Yanditse kuri Aime Christian', 'Page not found': 'Urupapuro ntirwabonetse', 'The page you are looking for does not exist or has moved.': 'Urupapuro ushaka ntirubaho cyangwa rwimuriwe ahandi.',
  },
};

const textSources = new WeakMap<Text, string>();
const attributeSources = new WeakMap<Element, Map<string, string>>();

const I18nContext = createContext<{ locale: Locale; setLocale: (locale: Locale) => void; t: (key: string) => string }>({ locale: 'en', setLocale: () => undefined, t: (key) => dictionaries.en[key] || key });

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const locale = useSyncExternalStore(
    (listener) => { window.addEventListener('ibyegeranyo-locale', listener); return () => window.removeEventListener('ibyegeranyo-locale', listener); },
    () => window.localStorage.getItem('ibyegeranyo-locale') === 'rw' ? 'rw' : 'en',
    () => 'en',
  ) as Locale;
  const value = useMemo(() => ({ locale, setLocale: (next: Locale) => { window.localStorage.setItem('ibyegeranyo-locale', next); document.documentElement.lang = next; window.dispatchEvent(new Event('ibyegeranyo-locale')); }, t: (key: string) => dictionaries[locale][key] || dictionaries.en[key] || key }), [locale]);
  useEffect(() => {
    const translate = (root: Node) => {
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
      let node: Text | null;
      while ((node = walker.nextNode() as Text | null)) {
        const parent = node.parentElement;
        if (!parent || ['SCRIPT', 'STYLE', 'CODE', 'OPTION'].includes(parent.tagName)) continue;
        const source = textSources.get(node) || node.nodeValue || '';
        textSources.set(node, source);
        const trimmed = source.trim(); const translated = dictionaries[locale][trimmed] || trimmed;
        if (trimmed && translated !== trimmed) node.nodeValue = source.replace(trimmed, translated);
        else if (locale === 'en') node.nodeValue = source;
      }
      const elements = root instanceof Element ? [root, ...root.querySelectorAll('[placeholder],[title],[aria-label]')] : Array.from(document.querySelectorAll('[placeholder],[title],[aria-label]'));
      elements.forEach((element) => ['placeholder', 'title', 'aria-label'].forEach((name) => {
        const current = element.getAttribute(name); if (!current) return;
        const sources = attributeSources.get(element) || new Map<string, string>(); const source = sources.get(name) || current;
        sources.set(name, source); attributeSources.set(element, sources); element.setAttribute(name, locale === 'rw' ? dictionaries.rw[source] || source : source);
      }));
    };
    translate(document.body);
    const observer = new MutationObserver((records) => records.forEach((record) => record.addedNodes.forEach(translate)));
    observer.observe(document.body, { childList: true, subtree: true });
    return () => observer.disconnect();
  }, [locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() { return useContext(I18nContext); }
